#Call libraries
import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin

#Class to select features using a boolean mask generated by the Genetic Algorithm and transform the input data accordingly
#class = represents a component with behavior + configuration/state
class FeatureSelector(BaseEstimator, TransformerMixin):
    """ 
        Select features using a boolean mask generated by the Genetic Algorithm
        
        40 processed features -> FeatureSelector -> 25 selected features
    """

    def __init__(self, selected_mask: np.ndarray) -> None:
        self.selected_mask = selected_mask

    def fit(
        self,
        X: np.ndarray,
        y: np.ndarray | None = None
    ) -> "FeatureSelector":
        return self

    def transform(
        self,
        X: np.ndarray
    ) -> np.ndarray:
        return X[:, self.selected_mask]